learming_logs_app/urls.py
"""Определяет схемы URL для learning_logs_app """

from . import views
from django.urls import path

urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
    path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from learning_log import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',  include(('users.urls', 'users'), namespace = 'users')),
    path('', include(('learming_logs_app.urls','learming_logs_app'), namespace = 'learming_logs_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Определяет схемы url для пользователей"""
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    # login page
    path('login/', LoginView.as_view(template_name="users/login_page.html"), name="login"),
    # logout page
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("update_profile/", views.update_profile, name="update_profile"),
]

learming_logs_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """Тема, которую изучет пользователь"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.text
    
class Entry(models.Model):
    """Информация выученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
            """Возвращает строковое представление модели"""
            return self.text[:50] + "..."

    class Meta:
        verbose_name_plural = 'entries'

        
            

learming_logs_app/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'class': 'form-control'})}

learming_logs_app/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def index(request):
    """Домашняя страница приложения Learning log"""
    return render(request, 'learming_logs_app/index.html')

@login_required
def topics(request):
    """displays a list of themes related to user"""
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learming_logs_app/topics.html', context)

@login_required
def topic(request, topic_id):
    """displays all records about single topic"""
    try:
        topic = Topic.objects.get(id=topic_id)
    except:
        raise Http404
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')


    paginator = Paginator(entries, 4)
    page = request.GET.get('page')
    try:
        entries = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        entries = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        entries = paginator.page(paginator.num_pages)

    context = {'topic': topic, 'entries': entries}
    return render(request, 'learming_logs_app/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялисть, создается пустая форма
        form = TopicForm()
    else:
        # Было отправлено что-то через POST, обрабатываем данные
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit = False)
            new_topic.owner = request.user
            new_topic.save()
            # return HttpResponseRedirect(reverse('learming_logs_app:topics'))
            return HttpResponseRedirect(reverse('users:profile'))

    context = {'form': form}
    return render(request, 'learming_logs_app/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Adds new info by chosen theme"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learming_logs_app:topic', args = [topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learming_logs_app/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Allows to edit selected entry"""
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance = entry)
    else:
        form = EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learming_logs_app:topic', args = [topic.id]))
    
    context = {'entry' : entry, 'topic' : topic, 'form' : form}
    return render(request, 'learming_logs_app/edit_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic

    entry.delete()
    
    return HttpResponseRedirect(reverse('learming_logs_app:topic', args = [topic.id]))

@login_required
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    topic.delete()

    return HttpResponseRedirect(reverse('users:profile'))

learming_logs_app/templates/learming_logs_app/base.html
{% load bootstrap3 %}
<!DOCTYPE html> <html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
       <title>Learning Log</title>
       {% bootstrap_css %}
       {% bootstrap_javascript jquery=1 %}
</head>

</head>
<body>
<!-- Статическая навигационная панель -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="glyphicon glyphicon-menu-hamburger"></span> 
    </button>
    <a class="navbar-brand" href="{% url 'learming_logs_app:index' %}">
            Learning Log</a>
        </div>
    <div id="navbar" class="navbar-collapse collapse"> <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
        <li><a href="{% url 'users:profile' %}">Hello, {{ user.username }}.</a></li>
        {% endif %}
        <!-- <li><a href="{% url 'learming_logs_app:topics' %}">Topics</a></li> -->
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'users:logout' %}?next={% url 'learming_logs_app:index'%}">log out</a></li>
            {% else %}
                <li><a href="{% url 'users:register' %}">register</a></li>
                <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
        </ul> 
    </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container"> <div class="page-header">
    {% block header %}{% endblock header %}
  </div>
  <div>
    {% block content %}{% endblock content %}
</div>
</div> <!-- /container -->
</body>
</html>

learming_logs_app/templates/learming_logs_app/edit_entry.html
{% extends "learming_logs_app/base.html" %}
{% block content %}

    <p><a href="{% url 'learming_logs_app:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>
    <form action="{% url 'learming_logs_app:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit changes</button>
    </form>

{% endblock content %}

learming_logs_app/templates/learming_logs_app/index.html
{% extends "learming_logs_app/base.html" %}

{% block header %}
    <div class='jumbotron'>
    <h1>Track your learning.</h1>
    <h4>
        {% if user.is_authenticated == False %}
            <a href="{% url 'users:register' %}">Register an account</a>
        {% else %}
        Create your first <a href="{% url 'learming_logs_app:new_topic' %}">Topic</a>
        {% endif %}
        to make your own Learning Log, and list the topics you're learning about.
    </h4>
    <h4>
        Whenever you learn something new about a topic, make an entry
        summarizing what you've learned. 
    </h4>
    {% if user.is_authenticated == False %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Get started</a>
    {% endif %}
    </div>
{% endblock header %}
{% block content %}
{% endblock content %}

learming_logs_app/templates/learming_logs_app/new_entry.html
{% extends "learming_logs_app/base.html" %}
{% block content %}

    <p><a href="{% url 'learming_logs_app:topic' topic.id %}">{{ topic }}</a></p>

    <h3>Add a new entry:</h3>
    <form action="{% url 'learming_logs_app:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="btn btn-primary">add entry</button>
    </form>

{% endblock content %}

learming_logs_app/templates/learming_logs_app/new_topic.html
{% extends "learming_logs_app/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'learming_logs_app:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
    </form>
{% endblock content %}

learming_logs_app/templates/learming_logs_app/topic.html
{% extends "learming_logs_app/base.html" %}
{% load static %}
{% block header %}
     <h3>{{ topic }}</h3>
{% endblock header %}

{% block content %}
    <p>
        <a href="{% url 'learming_logs_app:new_entry' topic.id %}">add new entry</a>
    </p>
        {% for entry in entries %}
            <div class="panel panel-default"> 
                <div class="panel-heading">
                    <h4>
                        {{ entry.date_added|date:'M d, Y H:i' }}
                        <small>
                            <a href="{% url 'learming_logs_app:edit_entry' entry.id %}"> edit entry</a>
                        </small>
                        <small>
                          {% url 'learming_logs_app:delete_entry' entry.id as the_url %}
                            <a href="#" class="pull-right" data-toggle="modal" data-target="#deleteEntryModal" 
                            onclick="updateModal('delEntryModalLink', '{{the_url}}')">delete entry</a>
                        </small>
                    </h4>
                </div>
                <div class="panel-body">
                    {{ entry.text|linebreaks }}
                </div>
            </div> <!-- panel -->
        {% empty %}
        {% url 'learming_logs_app:delete_topic' topic.id as the_url%}
            There are no entries for this topic yet. Would you like to <a href="#" data-toggle="modal" data-target="#deleteTopicModal"
            onclick="updateModal('deleteTopicModalLink','{{the_url}}')">delete</a> delete topic?
        {% endfor %}


      <nav aria-label="Page navigation example">
        <ul class="pagination">
        {% if entries.has_previous %}
        <li class="page-item">
          <a href="?page={{ entries.previous_page_number }}" class="page-link" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        {% for num in entries.paginator.page_range %}
          {% if num == entries.number %}
          <li class="page-item">
              <span class="current"><b>{{ num }}</b></span>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ num }}"> {{ num }}</a>
          </li>
          {% endif %} 
        {% endfor %}
        

        {% if entries.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ entries.next_page_number }}">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
        {% endif %}
        
        <!-- Modal windows -->
        <div class="modal fade" id="deleteEntryModal" tabindex="-1" role="dialog" aria-labelledby="deleteEntryModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteEntryModalLabel">Delete record?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Are you sure you want to delete this record? This action cannot be unchanged.
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <a href="#" class="btn btn-primary" id="delEntryModalLink">Delete</a>
                </div>
              </div>
            </div>
          </div>

          <div class="modal fade" id="deleteTopicModal" tabindex="-1" role="dialog" aria-labelledby="deleteTopicModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteTopicModalLabel">Delete topic?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Are you sure you want to delete this topic? This action cannot be unchanged.
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <a href="#" class="btn btn-primary" id="deleteTopicModalLink">Delete</a>
                </div>
              </div>
            </div>
          </div>
    <script src="{% static 'script.js' %}"></script>
{% endblock content %}

learming_logs_app/templates/learming_logs_app/topics.html
{% extends "learming_logs_app/base.html" %}
{% block header %}
    <h2>Topics</h2>
{% endblock header %}

{% block content %}
    <ul>
      {% for topic in topics %}
        <li>
          <h4>
            <a href="{% url 'learming_logs_app:topic' topic.id %}">{{ topic }}</a>
          </h4>
        </li>
      {% empty %}
        <li>No topics have been added yet.</li>
      {% endfor %}
    </ul>
    <h4><a href="{% url 'learming_logs_app:new_topic' %}"> Add a new topic</a></h4>
{% endblock content %}