learming_logs_app/urls.py
"""Определяет схемы URL для learning_logs_app """

from . import views
from django.urls import path

urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
    path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from learning_log import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',  include(('users.urls', 'users'), namespace = 'users')),
    path('', include(('learming_logs_app.urls','learming_logs_app'), namespace = 'learming_logs_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Определяет схемы url для пользователей"""
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    # login page
    path('login/', LoginView.as_view(template_name="users/login_page.html"), name="login"),
    # logout page
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("update_profile/", views.update_profile, name="update_profile"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    institution = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, widget=forms.FileInput)
    class Meta:
        model = Profile
        fields = ('institution', 'avatar',)

users/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.views import LogoutView
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from users.forms import UserForm, ProfileForm
from learming_logs_app.models import Topic
from django.contrib import messages

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learming_logs_app:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            authenticated_user = authenticate(username = new_user.username, password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learming_logs_app:index'))

    context = {'form' : form}
    return render(request, 'users/register.html', context)

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            messages.success(request, 'Form submission successful')
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('users:update_profile'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/update_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

@login_required
def profile(request):
    user = request.user
    profileData = request.user.profile
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {
        'image': profileData.avatar,
        'defaultImg': '/static/defaultUser.jpeg',
        'institution': profileData.institution,
        'topics': topics,
    }
    return render(request, 'users/profile.html', context)

users/templates/users/Login.html
{% extends 'learming_logs_app/base.html' %}
{% load bootstrap3 %}
{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learming_logs_app:index' %}" /> </form>
{% endblock content %}

users/templates/users/login_page.html
{% extends 'learming_logs_app/base.html' %}
{% load bootstrap3 %}
{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learming_logs_app:index' %}" /> </form>
{% endblock content %}

users/templates/users/profile.html
{% extends 'learming_logs_app/base.html' %}
{% load bootstrap3 %}
{% load widget_tweaks %}
{% block content %}

<div class="row">
    <div class="col-sm-3">
      <div class="thumbnail">
        {% if image %}
          <img src="{{ image.url }}" style="width:100%; max-width:250px;">
        {% else %}
          <img src="{{ defaultImg }}" style="width:100%; max-width:250px;">
        {% endif %}
        <div class="text-center"> 
          <a href="{% url 'users:update_profile' %}" class="btn btn-info" style="width:100%; max-width:250px;" role="button">
            settings
            <span class="glyphicon glyphicon-cog"></span>
          </a>
        </div> 
        <div class="caption">
          {% if user.first_name and user.last_name%}
            <h3>{{user.first_name}} {{user.last_name}}</h3>
          {% else %} 
            <small><li>no name provided</li></small>
          {%  endif %}
          {% if institution %}
            <p>{{institution}}</p>
          {% else %}
            <small><li>no institution provided</li></small>
          {%  endif %}
        </div>
      </div>
    </div>
    <div class="col-sm-9">
        <h2>Your topics</h2>
        <ul>
            {% for topic in topics %}
              <li>
                <h4>
                  <a href="{% url 'learming_logs_app:topic' topic.id %}">{{ topic }}</a>
                </h4>
              </li>
            {% empty %}
              <li>No topics have been added yet.</li>
            {% endfor %}
          </ul>
          <h4><a href="{% url 'learming_logs_app:new_topic' %}"> Add a new topic</a></h4>
    </div>
  </div>

{% endblock content %}

users/templates/users/register.html
{% extends 'learming_logs_app/base.html' %}
{% load bootstrap3 %}
{% load widget_tweaks %}
{% block content %}

<form method="POST" action="{% url 'users:register' %}">
    {% csrf_token%}

    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    {% endif %}

    <div class="form-group">
        <label for="username">Username</label>

        {{ form.username|add_class:"form-control"|attr:"id:username"|attr:"placeholder:Enter username"|attr:"aria-describedby:usernameHelp"}}
        
        <!-- <small id="usernameHelp" class="form-text text-muted">Some useful info.</small> -->
    </div>

    <div class="form-group">
        <label for="password1">Password</label>

        {{ form.password1|add_class:"form-control"|attr:"id:password1"|attr:"placeholder:Enter password"|attr:"aria-describedby:password1Help"}}
        
        <!-- <small id="password1Help" class="form-text text-muted">Some useful info.</small> -->
    </div>

    <div class="form-group">
        <label for="password1">Confirm password</label>

        {{ form.password2|add_class:"form-control"|attr:"id:password2"|attr:"placeholder:Repeat password"|attr:"aria-describedby:password2Help"}}
        
        <!-- <small id="password2Help" class="form-text text-muted">Some useful info.</small> -->
    </div>

    <button name="submit" class="btn btn-primary">register</button>

    <input type="hidden" name="next" value="{% url 'learming_logs_app:index' %}" />
</form>

{% endblock content %}

users/templates/users/update_profile.html
{% extends 'learming_logs_app/base.html' %}
{% load bootstrap3 %}
{% load widget_tweaks %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-sm-5">
            <h2>Profile info</h2>
            <form action="{% url 'users:update_profile' %}"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="firstName">First name</label>
                        {{ user_form.first_name|add_class:"form-control"|attr:"id:firstName"|attr:"placeholder:Enter first name"|attr:"aria-describedby:firstNameHelp"}}
                </div>
                <div class="form-group">
                    <label for="last_name">Last name</label>
                        {{ user_form.last_name|add_class:"form-control"|attr:"id:last_name"|attr:"placeholder:Enter first name"|attr:"aria-describedby:lastNameHelp"}}
                </div>
                <div class="form-group">
                    <label for="institution">Institution</label>
                        {{ profile_form.institution|add_class:"form-control"|attr:"id:institution"|attr:"placeholder:Enter a place where you study"|attr:"aria-describedby:institutionHelp"}}
                </div>
                <div class="form-group">
                    <label for="avatar">Profile photo</label>
                        {{ profile_form.avatar|attr:"id:avatar" }}
                </div>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </form>
        </div>
        <div class="col-sm-5">
            <h2>Security settings</h2>
            <p>in progress...</p>
        </div>
    </div>
{% endblock content %}